___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 fives

In [3]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [4]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Create an array of all the even integers from 10 to 50

In [5]:
np.arange(10, 50, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [6]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [10]:
np.random.rand()

0.29601820260618483

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [11]:
np.random.randn(25)

array([ 1.25799255, -0.23098173, -0.58060534, -0.76524385, -0.65347819,
        0.22466457,  0.18448163, -0.63336602, -0.17796238, -0.58779066,
        0.96369469, -0.59236478,  1.68886029,  2.5247431 ,  0.97508271,
        1.75526248, -1.70828158, -1.43906248,  0.36048794,  0.05950796,
       -0.96703261, -1.04605886, -1.12413919,  0.48937922,  1.10461834])

#### Create the following matrix:
### 10x10 matrix with values ranging from 0 to 1

In [14]:
np.random.rand(100).reshape(10,10)

array([[0.26937083, 0.08337036, 0.48521571, 0.82098733, 0.14989612,
        0.03384917, 0.01292542, 0.08684876, 0.10534371, 0.95546747],
       [0.06194598, 0.65014576, 0.72454256, 0.5105828 , 0.9454281 ,
        0.654447  , 0.38438739, 0.1520992 , 0.00633376, 0.7666007 ],
       [0.19119964, 0.20190676, 0.7642264 , 0.37971077, 0.65603037,
        0.2786829 , 0.64988479, 0.42092467, 0.5877269 , 0.00589388],
       [0.54352916, 0.56893008, 0.2724915 , 0.17026777, 0.63167495,
        0.19009243, 0.15903708, 0.53512838, 0.1595283 , 0.46671951],
       [0.37202433, 0.16141749, 0.39326345, 0.22681494, 0.66178317,
        0.41495211, 0.64793486, 0.22271456, 0.98242396, 0.98126439],
       [0.37530077, 0.14030357, 0.5346011 , 0.35883061, 0.62062304,
        0.26845013, 0.88937147, 0.54948794, 0.66190392, 0.28115256],
       [0.95756456, 0.46101082, 0.35665964, 0.97930396, 0.30617237,
        0.82318848, 0.71659794, 0.20322049, 0.55754108, 0.54997067],
       [0.86781746, 0.36468154, 0.1867156

#### Create an array of 20 linearly spaced points between 0 and 1:

In [15]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [18]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [20]:
arr[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [21]:
arr[3,4]

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [25]:
arr[0:3,1]

array([ 2,  7, 12])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [26]:
arr[4, :]

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [27]:
arr[3:, :]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [29]:
sum = 0
i = 0
j = 0

for i in arr:
    for j in i:
        sum += j

sum

325

In [31]:
arr.sum()

325

#### Get the standard deviation of the values in mat

In [32]:
arr.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [34]:
arr.sum(axis = 0)

array([55, 60, 65, 70, 75])

# Great Job!